server.port=4006

spring.datasource.url=jdbc:postgresql://postgres:5432/appointment_service_db
spring.datasource.username=admin_user
spring.datasource.password=password
spring.jpa.hibernate.ddl-auto=update
spring.sql.init.mode=always
spring.jpa.defer-datasource-initialization=true
